import Head from 'next/head'
import Link from 'next/link'
import React, {useState} from 'react';
import {
  CalendarOutlined,
  FolderOpenOutlined,
  FireOutlined
} from '@ant-design/icons';
import axios from 'axios'
import marked from 'marked'
import hljs from "highlight.js";
import 'highlight.js/styles/monokai-sublime.css';
import { Row, Col, List } from 'antd'
import Header from '../components/Header'
import Author from '../components/Author'
import Advert from '../components/Advert'
import Footer from '../components/Footer'
import  servicePath  from '../config/apiUrl'
import styles from '../styles/pages/Home.module.css'

const Home = (list) => {

  console.log(list);
  const [mylist, setMylist] = useState(list.data);

  const renderer = new marked.Renderer();
  marked.setOptions({
    renderer: renderer,
    gfm: true,
    pedantic: false,
    sanitize: false,
    tables: true,
    breaks: false,
    smartLists: true,
    smartypants: false,
    sanitize:false,
    xhtml: false,
    highlight: function (code) {
      return hljs.highlightAuto(code).value;
    }
  });

  return (
    <div>
      <Head>
        <title>Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header/>

      <Row className={styles.comm_main} type="flex" justify="center">
        <Col className={styles.comm_left} xs={24} sm={24} md={16} lg={18} xl={14}  >
          <List 
              header={<div>最新日志</div>}
              itemLayout="vertical"
              dataSource={mylist}
              renderItem={item => (
                  <List.Item>
                      <div className={styles.list_title}>
                        <Link href={{pathname:'/detailed', query:{id:item.id}}}>
                          <a>{item.title}</a>
                        </Link>
                      </div>
                      <div className={styles.list_icon}>
                        <span><CalendarOutlined />{item.addTime}</span>
                        <span><FolderOpenOutlined />{item.typeName}</span>
                        <span><FireOutlined />{item.view_count}</span>
                      </div>
                      <div 
                        className={styles.list_context}
                        dangerouslySetInnerHTML={{__html:marked(item.introduce)}}
                      ></div>  
                  </List.Item>
              )}
          />
        </Col>

        <Col className="comm_right" xs={0} sm={0} md={7} lg={5} xl={4}>
          <Author/>
          <Advert/>
        </Col>
      </Row>

      <Footer/>
    </div>
  )
}

Home.getInitialProps = async ()=>{
  const promise = new Promise((resolve)=>{
    axios(servicePath.getArticleList).then(
      (res)=>{
        console.log('远程获取数据结果:',res.data.data)
        resolve(res.data)
      }
    )
  })

  return await promise
}

export default Home;